language: ruby
cache: bundler
bundler_args: --without system_tests
script:
  - "bundle exec rspec spec/unit -fd -b"
env:
  - PUPPET_VERSION=4.3.0
  - PUPPET_VERSION=4.2.0
  - PUPPET_VERSION=4.1.0
  - PUPPET_VERSION=4.0.0
rvm:
  - 2.2.3
  - 2.2.0
  - 2.0.0

notifications:
  email: false