version: 0.1.0.{build}

environment:
  matrix:
  - AGENT_VERSION: 1.3.2
  - AGENT_VERSION: 1.2.7

install:
- SET PATH=C:\Ruby21\bin;%PATH%
- bundle install
- choco install puppet-agent --version %AGENT_VERSION%
build: off

test_script:
- bundle exec rake acceptance

notifications:
- provider: Email
  to:
  - somebody@somewhere.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false